// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/26/2026, 11:21:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/glebb/Desktop/pizza-frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/plugins/**/*.{js,ts,mjs}","/Users/glebb/Desktop/pizza-frontend/app/composables/**/*.{js,ts,mjs}","/Users/glebb/Desktop/pizza-frontend/app/utils/**/*.{js,ts,mjs}","/Users/glebb/Desktop/pizza-frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/glebb/Desktop/pizza-frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;